version: "3"

services:
  app:
    build:
      context: ./frontend
      target: base
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "3000:3000"
    command: npm run dev

  backend:
    build:
      context: ./backend
      target: base
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    command: npm run start:dev

  db:
    image: postgres:15-alpine
    volumes:
      - "postgres_data:/var/lib/postgresql/data/"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  prisma-studio:
    image: timothyjmiller/prisma-studio:latest
    restart: unless-stopped
    environment:
      - POSTGRES_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?schema=public
    ports:
      - 5555:5555
    depends_on:
      - db

volumes:
  postgres_data:
