import '@picocss/pico';
import './globals.scss';
import './components/Navbar';
import Navbar from './components/Navbar';

export const metadata = {
  title: 'FooBar GmbH Webshop',
  description: 'Generated by create next app',
  viewport: 'width=device-width, initital-scale=1',
  keywords: 'webshop, foobar',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="light">
      <body className="container">
        <Navbar />
        <main>{children}</main>
        <footer>
          <small>© 2021 FooBar GmbH</small>
        </footer>
      </body>
    </html>
  );
}
