apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: webshop-backend:1
          ports:
            - containerPort: 5000
          env:
           - name: DATABASE_URL
             valueFrom:
               secretKeyRef:
                 name: webshop-secrets
                 key: DATABASE_URL
          - name: C4_ENDPOINT
             valueFrom:
               configMapKeyRef:
                 name: webshop-config
                 key: C4_ENDPOINT
          - name: C4_API_KEY
              valueFrom:
                secretKeyRef:
                  name: webshop-secrets
                  key: C4_API_KEY
          - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: webshop-secrets
                  key: AWS_ACCESS_KEY
          - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: webshop-secrets
                  key: AWS_SECRET_ACCESS_KEY
          - name: SNS_TOPIC_ARN_REQUEST
              valueFrom:
                configMapKeyRef:
                  name: webshop-config
                  key: SNS_TOPIC_ARN_REQUEST
          - name: SNS_TOPIC_ARN_RESPONSE
              valueFrom:
                configMapKeyRef:
                  name: webshop-config
                  key: SNS_TOPIC_ARN_RESPONSE
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
